// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitaLink.Models.Data;

#nullable disable

namespace VitaLink.Migrations
{
    [DbContext(typeof(VitalinkDbContext))]
    [Migration("20251112152716_updating hsm idea")]
    partial class updatinghsmidea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vitalink.Models.AIRecommendation", b =>
                {
                    b.Property<int>("RecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationID"));

                    b.Property<string>("AlertMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FatigueLevel")
                        .HasColumnType("float");

                    b.Property<double>("OptimalIntensity")
                        .HasColumnType("float");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("RecommendationID");

                    b.HasIndex("SessionID");

                    b.ToTable("AIRecommendations");
                });

            modelBuilder.Entity("Vitalink.Models.AthleteProfile", b =>
                {
                    b.Property<string>("AthleteID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BeltID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TargetSport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("AthleteID");

                    b.HasIndex("BeltID")
                        .IsUnique()
                        .HasFilter("[BeltID] IS NOT NULL");

                    b.ToTable("AthleteProfiles");
                });

            modelBuilder.Entity("Vitalink.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AthleteID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Vitalink.Models.SensorDataRaw", b =>
                {
                    b.Property<string>("BeltID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("AccX")
                        .HasColumnType("real");

                    b.Property<float>("AccY")
                        .HasColumnType("real");

                    b.Property<float>("AccZ")
                        .HasColumnType("real");

                    b.Property<float>("HeartRate")
                        .HasColumnType("real");

                    b.Property<byte>("Spo2")
                        .HasColumnType("tinyint");

                    b.Property<int>("Sweat")
                        .HasColumnType("int");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<int?>("TrainingSessionSessionID")
                        .HasColumnType("int");

                    b.HasKey("BeltID");

                    b.HasIndex("TrainingSessionSessionID");

                    b.ToTable("SensorDataRaw");
                });

            modelBuilder.Entity("Vitalink.Models.SessionSummary", b =>
                {
                    b.Property<int>("SummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummaryID"));

                    b.Property<double>("AvgHeartRate")
                        .HasColumnType("float");

                    b.Property<double>("CaloriesBurned")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("FatigueScore_Final")
                        .HasColumnType("float");

                    b.Property<double>("MaxHeartRate")
                        .HasColumnType("float");

                    b.Property<double>("MaxMotionIntensity")
                        .HasColumnType("float");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.HasKey("SummaryID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.ToTable("SessionSummaries");
                });

            modelBuilder.Entity("Vitalink.Models.TrainingSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<string>("AthleteID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("time");

                    b.HasKey("SessionID");

                    b.HasIndex("AthleteID");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("Vitalink.Models.AIRecommendation", b =>
                {
                    b.HasOne("Vitalink.Models.TrainingSession", "TrainingSession")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Vitalink.Models.RefreshToken", b =>
                {
                    b.HasOne("Vitalink.Models.AthleteProfile", "Athlete")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AthleteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("Vitalink.Models.SensorDataRaw", b =>
                {
                    b.HasOne("Vitalink.Models.TrainingSession", null)
                        .WithMany("SensorDataRaw")
                        .HasForeignKey("TrainingSessionSessionID");
                });

            modelBuilder.Entity("Vitalink.Models.SessionSummary", b =>
                {
                    b.HasOne("Vitalink.Models.TrainingSession", "TrainingSession")
                        .WithOne("SessionSummary")
                        .HasForeignKey("Vitalink.Models.SessionSummary", "SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Vitalink.Models.TrainingSession", b =>
                {
                    b.HasOne("Vitalink.Models.AthleteProfile", "Athlete")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("AthleteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("Vitalink.Models.AthleteProfile", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("Vitalink.Models.TrainingSession", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("SensorDataRaw");

                    b.Navigation("SessionSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
